### PR TITLE
Add how to try tutorial without installation (by using Binder)

### PR DESCRIPTION
**Pull request by kozo2**

### CODE REVIEW

**Comment by bdemchak** [comment]
Thanks, Kozo –

 

I have added you as a contributor to the project, so you can add new changes directly.

 

(I did pull the #6 you submitted below.)

 

Thanks!

**Comment by kozo2** [comment]
@bdemchak 
(In addition)
Could you add `kozo2` (Read the Docs username of mine) to the maintainer of https://readthedocs.org/dashboard/py4cytoscape/users/
?

**Comment by bdemchak** [comment]
Done … please try it out …

**Comment by kozo2** [comment]
Thanks @bdemchak 
Now I can update (the settings of) https://py4cytoscape.readthedocs.io

**Pull request merged**
